// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Simulador.Api.Data;

#nullable disable

namespace Simulador.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251115231347_atualizando_entidades2")]
    partial class atualizando_entidades2
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.9");

            modelBuilder.Entity("Simulador.Api.Models.Cliente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("PerfilId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Pontuacao")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("PerfilId");

                    b.ToTable("Clientes");
                });

            modelBuilder.Entity("Simulador.Api.Models.Investimento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ClienteId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("Data")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("Rentabilidade")
                        .HasColumnType("TEXT");

                    b.Property<string>("Tipo")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("Valor")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ClienteId");

                    b.ToTable("Investimentos");
                });

            modelBuilder.Entity("Simulador.Api.Models.Perfil", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Descricao")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nome")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Perfis");
                });

            modelBuilder.Entity("Simulador.Api.Models.Produto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nome")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("Rentabilidade")
                        .HasColumnType("TEXT");

                    b.Property<string>("Risco")
                        .HasColumnType("TEXT");

                    b.Property<string>("Tipo")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Produtos");
                });

            modelBuilder.Entity("Simulador.Api.Models.Simulacao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ClienteId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DataSimulacao")
                        .HasColumnType("TEXT");

                    b.Property<int>("PrazoMeses")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Produto")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("ValorFinal")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("ValorInvestido")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Simulacoes");
                });

            modelBuilder.Entity("Simulador.Api.Simulador", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ClienteId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("DataSimulacao")
                        .HasColumnType("TEXT");

                    b.Property<int?>("PrazoMeses")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ProdutoId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal?>("ValorFinal")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("ValorInvestido")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ClienteId");

                    b.HasIndex("ProdutoId");

                    b.ToTable("Simuladores");
                });

            modelBuilder.Entity("Simulador.Api.Models.Cliente", b =>
                {
                    b.HasOne("Simulador.Api.Models.Perfil", "Perfil")
                        .WithMany()
                        .HasForeignKey("PerfilId");

                    b.Navigation("Perfil");
                });

            modelBuilder.Entity("Simulador.Api.Models.Investimento", b =>
                {
                    b.HasOne("Simulador.Api.Models.Cliente", "Cliente")
                        .WithMany()
                        .HasForeignKey("ClienteId");

                    b.Navigation("Cliente");
                });

            modelBuilder.Entity("Simulador.Api.Simulador", b =>
                {
                    b.HasOne("Simulador.Api.Models.Cliente", "Cliente")
                        .WithMany()
                        .HasForeignKey("ClienteId");

                    b.HasOne("Simulador.Api.Models.Produto", "Produto")
                        .WithMany()
                        .HasForeignKey("ProdutoId");

                    b.Navigation("Cliente");

                    b.Navigation("Produto");
                });
#pragma warning restore 612, 618
        }
    }
}
