# Etapa 1: Build da aplicação
FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
WORKDIR /src

# Copia o arquivo de projeto e restaura dependências
COPY Simulador.Api.csproj ./
RUN dotnet restore

# Copia o restante da aplicação
COPY . .

# Publica em Release
RUN dotnet publish -c Release -o /app/publish


# Etapa 2: Runtime
FROM mcr.microsoft.com/dotnet/aspnet:8.0 AS final
WORKDIR /app

# Copia arquivos publicados
COPY --from=build /app/publish .

# Permissões para o SQLite
RUN chmod -R 777 /app

# Expõe a porta padrão do ASP.NET no container
EXPOSE 8080

# Start
ENTRYPOINT ["dotnet", "Simulador.Api.dll"]

